server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jworker?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: supreium
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5       # 初始连接数
      max-active: 20        # 最大连接数
      min-idle: 5           # 最小空闲连接数
      max-wait: 60000       # 获取连接的最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000 # 连接间隔多久进行一次空闲连接检测
      min-evictable-idle-time-millis: 300000   # 连接保持空闲而不被驱逐的最小时间
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 127.0.0.1  # IP
    port: 6379 # 端口号
    password: Sh1chu@ng
    timeout: 10000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      columnFormat: '`%s`'
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0